# Generated by Django 3.1 on 2020-09-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
